name: Check public sites

on:
  #schedule:
  #  - cron: '*/5 * * * *'

  # manual trigger
  workflow_dispatch:

jobs:
  public-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check http status of sites
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["${{ secrets.MONITOR_PUBLIC_URLS }}"]'
          topic: "${{ secrets.NOTIFY_TOPIC }}"
          expected: '[200]'
      - name: ntfy-failed-notifications
        uses: niniyas/ntfy-action@master
        if: failure()
        with:
          url: 'https://ntfy.sh'
          topic: '$topic'
          priority: 5
          tags: +1,action,failed
          details: Site down!
